-- AlterTable
ALTER TABLE "ReceiptSettings" ADD COLUMN     "accentColor" TEXT DEFAULT '#666666',
ADD COLUMN     "autoPrint" BOOLEAN DEFAULT false,
ADD COLUMN     "currency" TEXT DEFAULT 'USD',
ADD COLUMN     "currencyPosition" TEXT DEFAULT 'before',
ADD COLUMN     "currencySymbol" TEXT DEFAULT '$',
ADD COLUMN     "customQrContent" TEXT,
ADD COLUMN     "fontFamily" TEXT DEFAULT 'monospace',
ADD COLUMN     "fontSize" TEXT DEFAULT 'normal',
ADD COLUMN     "footerMessage" TEXT,
ADD COLUMN     "headerMessage" TEXT,
ADD COLUMN     "language" TEXT DEFAULT 'en',
ADD COLUMN     "lineSpacing" TEXT DEFAULT 'normal',
ADD COLUMN     "logoUrl" TEXT,
ADD COLUMN     "paperSize" TEXT DEFAULT '80mm',
ADD COLUMN     "primaryColor" TEXT DEFAULT '#000000',
ADD COLUMN     "printCopyCount" INTEGER DEFAULT 1,
ADD COLUMN     "printDensity" TEXT DEFAULT 'normal',
ADD COLUMN     "qrCodeContent" TEXT DEFAULT 'website',
ADD COLUMN     "receiptTitle" TEXT,
ADD COLUMN     "showBalance" BOOLEAN DEFAULT true,
ADD COLUMN     "showCashierInfo" BOOLEAN DEFAULT true,
ADD COLUMN     "showCustomerInfo" BOOLEAN DEFAULT true,
ADD COLUMN     "showItemCodes" BOOLEAN DEFAULT true,
ADD COLUMN     "showItemDescriptions" BOOLEAN DEFAULT true,
ADD COLUMN     "showItemNumbers" BOOLEAN DEFAULT true,
ADD COLUMN     "showLogo" BOOLEAN DEFAULT true,
ADD COLUMN     "showPaymentMethods" BOOLEAN DEFAULT true,
ADD COLUMN     "showQrCode" BOOLEAN DEFAULT true,
ADD COLUMN     "showRunningTotal" BOOLEAN DEFAULT false,
ADD COLUMN     "showTaxBreakdown" BOOLEAN DEFAULT true,
ADD COLUMN     "showTimestamp" BOOLEAN DEFAULT true,
ADD COLUMN     "use24HourFormat" BOOLEAN DEFAULT false;
